apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whole-cluster-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/gitops-repo.git # Your GitOps repo URL
    targetRevision: HEAD # Or a specific branch like 'main'
    path: ./ # Points to the root of your GitOps repository
  destination:
    server: https://kubernetes.default.svc
    namespace: default # Or the namespace where you want the general app to land
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Important for creating namespaces if defined in Kustomization
      - ApplyOutOfSyncOnly=true # Can be useful for large syncs