apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-shared-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
